-- staging tables for dim/fact tables for data that is
-- 1. generated using python scripts
-- 2. csv taken from kaggle

CREATE TABLE staging.stg_customer (
    customer_business_key INTEGER,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    country VARCHAR(50),
    load_timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE staging.stg_store (
    city VARCHAR(200),
    city_ascii VARCHAR(200),
    lat NUMERIC(9,6),
    lng NUMERIC(9,6),
    country VARCHAR(50),
    iso2 VARCHAR(10),
    iso3 VARCHAR(10),
    admin_name VARCHAR(100),
    capital VARCHAR(50),
    population VARCHAR(20),
    id INTEGER,
    load_timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE staging.stg_product (
    product_business_key INTEGER,
    product_name VARCHAR(300),
    category VARCHAR(100),
    subcategory VARCHAR(100),
    load_timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE staging.stg_sales (
    date_key INTEGER,
    customer_business_key INTEGER,
    store_business_key INTEGER,
    product_business_key INTEGER,
    transaction_id INTEGER,
    quantity INTEGER,
    unit_price DECIMAL(10,2),
    load_timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE staging.stg_reviews (
    review_id TEXT,
    review_date DATE,
    customer_business_key INTEGER,
    product_business_key INTEGER,
    rating INTEGER,
    review_text TEXT,
    sentiment_score NUMERIC(4,2),
    raw_source JSONB
);


-- Dimension Date
CREATE TABLE dwh.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL,
    year_number INTEGER NOT NULL,
    month_number INTEGER NOT NULL,
    month_name VARCHAR(20),
    quarter_number INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL,
    is_weekend BOOLEAN NOT NULL
);

-- Dimension Customer
CREATE TABLE dwh.dim_customer (
    customer_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_business_key INTEGER NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    country VARCHAR(50),
    -- SCD Type 2
    valid_from TIMESTAMP NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMP,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 1
);

-- 1 active current record per customer only
CREATE UNIQUE INDEX uq_dim_customer_business_current
ON dwh.dim_customer (customer_business_key)
WHERE is_current = TRUE;

-- Dimension Store
CREATE TABLE dwh.dim_store (
    store_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_business_key INTEGER NOT NULL UNIQUE,
    store_name VARCHAR(200),
    city VARCHAR(100),
    country VARCHAR(50),
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    country_code CHAR(2),
    admin_name VARCHAR(100),
    population BIGINT
);

-- Dimension Product
CREATE TABLE dwh.dim_product (
    product_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- !!dropped the unique constraint here, added the unique index
    product_business_key INTEGER NOT NULL,
    product_name VARCHAR(300),
    category VARCHAR(100),
    subcategory VARCHAR(100),
    -- SCD Type 2
    valid_from TIMESTAMP NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMP,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 1
);

-- 1 active current record per product only
CREATE UNIQUE INDEX uq_dim_product_business_current
ON dwh.dim_product (product_business_key)
WHERE is_current = TRUE;

-- Fact Sales
CREATE TABLE dwh.fact_sales (
    sales_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key INTEGER NOT NULL,
    customer_key INTEGER NOT NULL,
    store_key INTEGER NOT NULL,
    product_key INTEGER NOT NULL,
    transaction_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    
    CONSTRAINT fk_sales_date FOREIGN KEY (date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_key) REFERENCES dwh.dim_customer(customer_key),
    CONSTRAINT fk_sales_store FOREIGN KEY (store_key) REFERENCES dwh.dim_store(store_key),
    CONSTRAINT fk_sales_product FOREIGN KEY (product_key) REFERENCES dwh.dim_product(product_key)
);

-- Fact review
CREATE TABLE dwh.fact_reviews (
    review_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key INTEGER NOT NULL,
    customer_key INTEGER NOT NULL,
    product_key INTEGER NOT NULL,
    rating INTEGER CHECK (rating BETWEEN 1 AND 5),
    review_text TEXT,
    sentiment_score NUMERIC(3,2),
    created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_review_date FOREIGN KEY (date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_review_customer FOREIGN KEY (customer_key) REFERENCES dwh.dim_customer(customer_key),
    CONSTRAINT fk_review_product FOREIGN KEY (product_key) REFERENCES dwh.dim_product(product_key)
);
